### ISSUE TITLE
RuntimeWarning: The unoptimized RealESRGAN is slow on CPU

### ISSUE THREAD

**Issue by cvar66** [sczhou/CodeFormer#34] opened 2022-09-15 19:48 UTC
When running codeformer I get this error. Not sure how to fix it.

inference_codeformer.py:22: RuntimeWarning: The unoptimized RealESRGAN is slow on CPU. We do not use it. If you really want to use it, please modify the corresponding codes.
  warnings.warn('The unoptimized RealESRGAN is slow on CPU. We do not use it. '

**Comment by sczhou** [comment] 2022-09-16 10:26
Please check the answer and discussion in #23

---
duplicate of #23

**Closed by sczhou** 2022-09-16 10:26 UTC
