### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by PengQiTu** [sczhou/CodeFormer#11] opened 2022-08-01 03:23 UTC
Hi, I'm very interested in your great work! I want to know when will the training code be released?

**Comment by sczhou** [comment] 2022-08-01 08:52
Hi @PengQiTu, thanks for your interest, since this paper is under review now, we plan to release the training code and other models after the paper is accepted.

**Comment by sczhou** [comment] 2022-08-01 09:01
Duplicate of #2

**Closed by sczhou** 2022-08-01 09:01 UTC
